apiVersion: skaffold/v2alpha3
kind: config
deploy:
  kubectl: 
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build: 
  # local: 
  #   push: false
  googleCloudBuild:
    projectId: pacific-destiny-272719
  artifacts: 
    - image: btchavez/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: btchavez/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: btchavez/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: btchavez/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: btchavez/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .